### ISSUE TITLE
May I see how you solve leetcode 33

### ISSUE THREAD

**Issue by Xanonymous-GitHub** [ricky9667/Leetcode-Solutions#1]
## Description

<p align="center">
<img align="center" src="https://github.com/user-attachments/assets/256b88e6-8aa3-4848-a6d6-7fdc4979f086" width="200">
</p>

After I finally AC leetcode 33, I couldn't find any other solutions that makes me feel inspiring.
Thus I'd like to seek for your version, if it's convenient for you. 🥹

Btw I'd also suggest solving leetcode 153 too. It's an easier version of 33.

- 33 https://leetcode.com/problems/search-in-rotated-sorted-array/
- 153 https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/

**Comment by ricky9667** [comment]
Haven't solved these yet, I'll put these into my task list and I'll reach out to you if I solved it. 😉

**Comment by Xanonymous-GitHub** [comment]
Thanks bro

**Comment by ricky9667** [comment]
BTW just had some clues just looking at the problems, maybe we can find a good solution using remainders?

**Comment by Xanonymous-GitHub** [comment]
I'm not quite sure at this, as I haven't thought about using remainders XD

**Comment by Xanonymous-GitHub** [comment]
Do u mean divide every numbers ... and ... ? I'm sorry but seems I didn't really get you 🥹

**Comment by ricky9667** [comment]
Oh I was thinking about `index % size` and do binary search instead of searching with pure index, but I haven't come up with  an entire solution yet.
If you understand you can implement it first and I can discuss with you after that :)

**Comment by ricky9667** [comment]
@Xanonymous-GitHub solved these two problems next to you yesterday, feel free to take a look 😎

- [153. Find Minimum in Rotated Sorted Array](https://github.com/ricky9667/Leetcode-Solutions/tree/master/153)
- [33. Search in Rotated Sorted Array](https://github.com/ricky9667/Leetcode-Solutions/tree/master/33)

However, these solutions are not as efficient as other submissions on Leetcode even my solutions are `O(logn)`, maybe we can discuss this problem someday 😉
